# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pos-hello"
client_id = "7ffc7ce44acdc8ce5784ec21a4230563"
application_url = "https://lang-trackback-technique-honolulu.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lang-trackback-technique-honolulu.trycloudflare.com/auth/callback",
  "https://lang-trackback-technique-honolulu.trycloudflare.com/auth/shopify/callback",
  "https://lang-trackback-technique-honolulu.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shadhin-dev-store-2.myshopify.com"
